### ISSUE TITLE
README.md missing info on resources

### ISSUE THREAD

**Issue by mbreakey3** [PowerShell/xWebAdministration#207]
Currently information on these resources is not included in the readme file:
-xIisFeatureDelegation
-xIisHandler
-xIisMimeTypeMapping
-xWebAppPoolDefaults
-xWebSiteDefaults

**Comment by hahndorf** [comment]
I checked my logs and found some information I wrote when I created some of those resource, due to some merging conflicts they never made it into the pull request:

### xIisFeatureDelegation
* **SectionName**: relative path of the section to delegate such as **security/authentication**
* **OverrideMode**: Mode of that section { **Allow** | **Deny** }

### xIisMimeTypeMapping
* **Extension**: The file extension to map such as **.html**
* **MimeType**: The MIME type to map that extension to such as **text/html**
* **Ensure**: Ensures that the MIME type mapping is **Present** or **Absent**.

### xWebAppPoolDefaults
* **ApplyTo**: Required Key value, always **Machine**
* **ManagedRuntimeVersion**: CLR Version {v2.0|v4.0|} empty string for unmanaged.
* **ApplicationPoolIdentity**: {ApplicationPoolIdentity | LocalService |LocalSystem | NetworkService}

**Comment by mbreakey3** [comment]
Great! Thank you for re-providing this information. Yeah, we recently updated the way that we merge PRs, we've had a few issues in the past about changes being overwritten.

**Comment by mbreakey3** [comment]
If you have time, could you open a PR for this with these changes and I can get it merged?

**Comment by hahndorf** [comment]
Hi Maria,

I think I tried that before and I just tried again now. I merged my fork with the latest dev branch, updated the readme.md and committed back into my fork. After creating a Pull Request, I have three tests failing in appveyor. I expected using the lastest dev and not changing any code, the tests should pass. I'm not sure what I'm doing wrong. This is PR #237

**Comment by mbreakey3** [comment]
@hahndorf - Yes, it looks like you also changed the mof for xWebApplication - AuthenticationInfo used to be a String, but now it's an array of Strings so there's a mismatch between the mof and the .psm1

**Comment by johlju** [comment]
To me all properties are present in the README.md, this was fixed in PR #237. Closing this issue as resolved.
