### ISSUE TITLE
xWebApplication: regression in #220. PhysicalPath issue.

### ISSUE THREAD

**Issue by SNikalaichyk** [PowerShell/xWebAdministration#222]
Hi @gigi81,
#220 does not seem to work as expected: WebAppPool is now being updated, PhysicalPath is no more.
Change on line 157 breaks setting of the PhysicalPath property.

In #30 I fixed setting PhysicalPath, WebAppPool was working as expected too. It seems that both issues were reintroduced since then.

**Comment by gigi81** [comment]
Hi @SNikalaichyk 
Correct me if I'm wrong, but it seems from #30 that while settings the PhysicalPath, the Filter parameters needs to be:
```powershell
-Filter "$($webApplication.ItemXPath)/virtualDirectory[@path='/']"
```
While for the apppool it needs to be just:
```powershell
-Filter $webApplication.ItemXPath
```

I changed both because the webapppool was wrong and not working (someone add the virtualDirectory[@path='/'] to it as well) and assumed PhysicalPath needed the same fix. I also checked the documentation of Set-WebConfigurationProperty and it seemed to be correct.
If you confirm the above, we should just fix the PhysicalPath part and add a nice comment to explain the above. Agree?

**Comment by SNikalaichyk** [comment]
@gigi81 ,
I confirm. Let's do it.

**Comment by gigi81** [comment]
@SNikalaichyk Great! I'm busy right now. You can go ahead if you have time now or I can do it later today or tomorrow.

**Comment by SNikalaichyk** [comment]
@gigi81 ,
Please do it when you have time. It's not urgent.

**Comment by gigi81** [comment]
@SNikalaichyk 
done! sorry for the delay

**Comment by emitodiaz** [comment]
Hi!

I think that the code inside "Update Physical Path" and "Update AppPool" it's not working very well when you have a Web Application inside a WebApplication, example:

WepAppPrincipal
  - WebChild1
  - WebChild2

I was trying and watching the code inside and looks like that a checking for NULL it's missing??? (what do you think???)

if (($PSBoundParameters.ContainsKey('PhysicalPath') -and `
                $webApplication.physicalPath -ne $PhysicalPath)
here I add:
**-and ($webApplication.physicalPath -ne $null) )**

Because if I not checkin for null giveme the message:
Argument Filter is null blablablabla.

Any one else having the same issue?
Thanks.
Emiliano.
