### ISSUE TITLE
Offline install of module

### ISSUE THREAD

**Issue by svenschelfaut** [PowerShell/xWebAdministration#238]
I want to use the xWebAdministration module offline, I placed it in the correct Powershell modules folder but when executing my script I keep receiving  "Unable to load module 'xWebAdministration': module not found."

**Comment by huwparker** [comment]
Where have you placed it?  I've experienced similar when I've inadvertently placed it in "C:\Program Files (x86)\WindowsPowerShell" rather than  "C:\Program Files\WindowsPowerShell".  The other gotcha seems to be to have a version number folder underneath xWebAdministration (eg C:\Program Files\WindowsPowerShell\Modules\xWebAdministration\1.13.0.0).  Moving the files and folders from 1.13.0.0 to the xWebAdministration folder resolved my issue.

HTH

**Comment by svenschelfaut** [comment]
Already found it myself: it was indeed the version number folder that caused the problem.
