### ISSUE TITLE
Add Support for additional configuration sections in xWebConfigKeyValue

### ISSUE THREAD

**Issue by VeitSanner** [PowerShell/xWebAdministration#249]
As per the description xWebConfigKeyValue currently only supports to set configuration values in the AppSettings sections. I would like to have the possibility to verify and set the configuration in other sections as well, e.g. connections strings.

Are there any plans to provide this feature?

**Comment by mbreakey3** [comment]
I believe that setting the configuration values in AppSettings was the simplest to implement. Adding functionality to set other sections would certainly be a great improvement, and you're welcome to open a PR for that if you would like. Otherwise, I'm not sure what the timeline is for extending this resource on our end.

**Comment by turkeys-united** [comment]
We have a need to ensure a range of config settings are maintained in a desired state as part of our IIS hardening policy, so a resource that lets us maintain more than just appSettings would be highly desirable! Before I start working on implementing this myself, I just wanted to check in to see if any progress had been made on this front since these comments close to a year ago?

**Comment by mbreakey3** [comment]
We haven't been able to put much focus on this module lately, so no - as far as I know, there hasn't been any work on implementing this feature yet.

**Comment by rosberglinhares** [comment]
I already have code for the _connectionStrings_ and _machineKey_ sections. Should these configurations be in this resource? Or does it make more sense to have new xWebConfigConnectionString and xWebConfigMachineKey resources?

**Comment by turkeys-united** [comment]
I've created 2 new resources that I've named cWebConfigProperty & cWebConfigPropertyCollection respectively. The cWebConfigProperty resource focuses on ensuring the value of an attribute of a non-repeating element in config files. The cWebConfigPropertyCollection resource on the other hand is intended for ensuring the value of an attribute of a potentially repeating element that is keyed. I've created this resource to be generic in what property collections is caters for, so it can handle e.g. appSettings, connectionStrings, verbs, logDefinitions etc.
I'm just working through tidying up the code & unit tests to align with the standards for contribution then I'll submit a pull request. Hopefully in the next week or so.

**Comment by turkeys-united** [comment]
Hi @mbreakey3, I noted in the contribution guidelines that I need to ask permission before starting work on an issue without the "help wanted" label... I have code & tests ready to contribute for this issue, can I please pick this one up?

**Comment by PlagueHO** [comment]
Hi @turkeys-united - the help is always gratefully accepted! One of the [maintainers](https://github.com/PowerShell/DscResources/blob/master/Maintainers.md) for this repo can mark this issue as in progress so that the community knows you are working on it. The maintainer for this repo is @tysonjhayes - Tyson, are you able to mark this as in progress for @turkeys-united?

**Comment by regedit32** [comment]
Could this be as simple as removing the current validateSet of 'AppSettings' on the $ConfigSection parameter?  This would allow a user to specify any Configuration Section path they wanted and should work as-is.

**Comment by turkeys-united** [comment]
I submitted https://github.com/PowerShell/xWebAdministration/pull/330 a while back to address this, just wondering if anyone's had / will have a chance to review any time soon? Thanks!

**Comment by mavratar** [comment]
Initial testing of xWebConfigProperty_Add resource has allowed me to to set certain configuration settings outside of AppSettings.  I am having an issue setting configuration settings that have their section locked.  I would think that during the Get/Set/Test phase locked sections would become unlocked to make changes and then locked again.

**Comment by turkeys-united** [comment]
@mavratar Thanks for taking a look.
Your suggestion certainly sounds like it could be a useful feature, although I don't have any plans to introduce it at this stage. Have you found that other resources in the xWebAdministration module that result in changes to config files _do_ perform this for you? I'm wary of extending these new resources in a way that's inconsistent with how other resources behave, and also of introducing side-effects to what this resource does - for instance it could actually be invalid or unauthorised for a particular setting to be modified (set higher in the configuration hierarchy) which is why the section is locked.

**Comment by mavratar** [comment]
Hello, I have found that xIisFeatureDelegation allows write access to sections that normally don’t have it.  The problem I’m running into is that once I re-lock the section using xIisFeatureDelegation, my Get-DscConfiguration and Test-DscConfiguration fail because the section is locked again.  I understand the concerns you have about introducing side-effects and do appreciate the work you’ve done to get me this far.  Thank you.


Regards,

Mark Vrataric
Consultant
Mobile: 1.443.201.4072
mark.vrataric@microsoft.com
