### ISSUE TITLE
xWebAppPoolIdentity resource available but needs community assistance

### ISSUE THREAD

**Issue by mgreenegit** [PowerShell/xWebAdministration#252]
Additions have been made to this module in a separate repo:
[https://github.com/robwi/xWebAdministration](https://github.com/robwi/xWebAdministration)

HELP WANTED

If someone would like to review this work and incorporate changes back to the resource kit as a new PR, that would be a great project.

**Comment by SNikalaichyk** [comment]
Hi @mgreenegit ,
This seems unnecessary, because **xWebAppPool** already supports setting Application Pool Identity:
* **identityType** : Indicates the account identity under which the application pool runs.
    The values that are allowed for this property are: `ApplicationPoolIdentity`, `LocalService`, `LocalSystem`, `NetworkService`, and `SpecificUser`.
* **Credential** : Indicates the custom account crededentials. This property is only valid when the **identityType** property is set to `SpecificUser`.

**Comment by csharmath** [comment]
> xWebAppPool already supports setting Application Pool Identity
Except gMSA. Is anyone working on adding support for gMSA identity ?

**Comment by johlju** [comment]
@csharmath We are tracking MSA and gMSA here https://github.com/PowerShell/xWebAdministration/issues/80

**Comment by johlju** [comment]
Closing this issue as per @SNikalaichyk comment.
