### ISSUE TITLE
xWebAppPool & Secure MOF credentials

### ISSUE THREAD

**Issue by jhenders1973** [PowerShell/xWebAdministration#301]
I have an issue where the App Pool fails to start due to "bad password". I know my config/code is good as the .mof shows an encrypted password and then i see on the node that the password is decrypted but trying to start the pools gives me bad username/password error. If i then manually enter the same password the pool starts....this only happens for pools that currently exist, not if i create a new one. So again, i know the process is good, my code is good..the certicate is correct etc so maybe this is something to do with how IIS is storing/seeing this encrypted/decrypted credential????
Any help would be awesome.
Thanks

**Comment by jwainwright** [comment]
My systems are seeing the same exact issue. It happens at first I thought I was reaching the MaxEnvelopeSizekb (defaults to 500), but even after increasing that  10000, I still see the same behaviors. In many cases, I have 10 plus application pools on servers that experience this, but only a small handful of the application pools will experience this issue on the same server. It has been debilitating enough that we have had to stop the consistency scheduled tasks.

**Comment by jhenders1973** [comment]
It´s seems like the Protect/Unprotect-CMS Message is not working correctly....it´s very confusing! If i run **Get-CimInstance -Namespace root/MicrosoftIISv2 -ClassName IIsApplicationPoolSetting -Property WAMUserName, WAMUserPass | select  name, WAMUserName, WAMUserPass** i see all my IIS AppPool Username/Passwords in plaintext. I see the password as the encrypted key - -----BEGIN CMS------ but i know the decryption Works because on a NEW pool the pool starts but for an existing pool it says bad password. Maybe it´s at a lower/deeper level...local Security policy or GPO being applied at domain level??? On a test node i have it seems to work perfectly.....sort of!

**Comment by jwainwright** [comment]
I am opening a ticket with MS to find a solution. I have experienced the exact same issue. My assumption is that you are running a pull configuration as well. Did you know about exhausting the MaxEnvelopeSize? 
Get-Item WSMan:\Localhost\MaxEnvelopeSizeKB. 
If you grab the MOF  from the pull server, rename it to the destination servers name, and run it on the destination server:
Start-DSCConfiguration -Path <path of the mof> -wait -force -verbose
You can see if you are hitting the MaxEnvelopeSizeKB limit.
I was hitting that 1st, but now it does not show any error of value.(That I can tell)

**Comment by jhenders1973** [comment]
I opened a ticket with Microsoft.... They do not support it...these modules
are open source 'experimental'.

You have to speak to the person that wrote the module or open a case on
github....which is what we have done.

John

**Comment by jwainwright** [comment]
Yea... you have to get them to escalate to the right group. Spent today getting them to understand why they need to escalate. Hoping when they call me back tomorrow they will get me to the right group.

**Comment by dchristian3188** [comment]
What version of PowerShell are you guys running on the machines seeing the issue and generating the mof? We saw similar behavior when there was a mismatch between the two.

**Comment by jwainwright** [comment]
Source
5      1      14393  1066
Destination
4      0      -1     -1
Will try your suggestion and let you know what I get from it.

**Comment by tysonjhayes** [comment]
Hi all. Could I get some example configs that are failing? Could I also get some log samples of where the credentials are being set? I'm just trying to narrow down where in the code we are potentially seeing some problems.

My current theory is that [L402](https://github.com/PowerShell/xWebAdministration/blob/dev/DSCResources/MSFT_xWebAppPool/MSFT_xWebAppPool.psm1#L402) is what's failing but I'll need some logs to confirm. 

As a troubleshooting step (which I do not recommend doing this in production or with passwords that you care about) you could add Write-Verbose "[Password] $clearTextPassword" and Write-Verbose "[AppConfig] $appPool.processModel.password" after line 402. This would output whatever got decrypted by Get-Credential and whatever it found in the app pool.  You could do the same thing around 772 which would do it on the test but it sounds like the failure is in the set.

Please note the above is super insecure, and I don't recommend doing it in production, or at least not with an account you actually care about leaking. 😁

**Comment by jwainwright** [comment]
Hey @tysonjhayes Thanks for taking a look. Would love to send you the configs(MOF? or something else?), but not sure how to. As for the logs, are you speaking of the DSC operational event log, or the -verbose from apply the MOF directly? The $appPool.processModel.password shows the encrypted string after run on effected pools. Which is why my theory is that we are over running some buffer/max level of something.(already found and increased the MaxEnvelopeSize)  The funny thing is that it works some times and not others. Another indicator that this is a problem with hitting a MAX limitation is that appears to be the same Application pools(not all of the appPools that we are applying) over and over and they are the ones hit later in the process.

**Comment by tysonjhayes** [comment]
@jwainwright - The -Verbose log I find to be more useful and easier to cut and paste. 😁 Honestly putting in the issue is the easiest way to go, you can snip it down to the relevant parts. This way everyone who wants to jump in can try to troubleshoot along from home. If you are uncomfortable with that let me know and we'll figure out some way for you to get it to me.

How big is the mof file we're dealing with? When changing the maxenvelopesize was there a change in how many would succeed/fail? ie: before changing it would fail 20% (ie if you have 100 the last 20 fails) of the time vs after change it does 10%.

**Comment by jwainwright** [comment]
@tysonjhayes - So to answer the second paragraph 1st. The MOF files sizes are large as 1 mb and go down to around 400 kb.(At least the ones I can confirm have seen the issue) As for the MaxEnvelopeSize change, yes we saw a difference. initially, it seemed 30% would fail, but after changing the MaxEnvelopeSize it appeared closer to 50-70%. I have not successfully been able to get debug to record while the problem is happening... I am extending the log size and trying again... did not realize the event logs were only 1k by default. The biggest problem is the inconsistency... if I do not have it running in several environments, it can take some time to trigger. Although, the large MOF files seem to trigger more often.

**Comment by jhenders1973** [comment]
Hi, sorry for not commenting for a while...death in the family! :( Have we got any further in understanding this issue? I am having a real battle my Security team about storing plain txt passwords in my MOF files.

**Comment by Tom-Gray** [comment]
I am seeing the exact issue described in the original post. 

Encrypting some domain credentials to use for the App Pool identity. The usernames are applied but whatever gets applied as a password does not work.

**Comment by jhenders1973** [comment]
Hi....i gave up in the end and just worked out a compromise with my Security team. It´s a really odd issue and must have something to do with how the password is being decrypted.

**Comment by Tom-Gray** [comment]
I went ahead and echoed the plaintext password variable as suggested by @tysonjhayes and the $clearTextPassword variable reports the correct password that I'm giving it. 

`$clearTextPassword = $Credential.GetNetworkCredential().Password
                    write-verbose "decrypted password reporting as: $clearTextPassword"

                    if ($appPool.processModel.password -cne $clearTextPassword)
                    {
                        Write-Verbose -Message (
                            $LocalizedData['VerboseSetProperty'] -f 'Credential (password)', $Name
                        )

                        Invoke-AppCmd -ArgumentList 'set', 'apppool', $Name, (
                            '/processModel.password:{0}' -f $clearTextPassword
                        )
                    }`

Unfortunately `Write-Verbose "[AppConfig] $appPool.processModel.password" ` only returns * Microsoft.IIs.PowerShell.Framework.ConfigurationElement.processModel.password* which isn't helpful. I need some guidance about returning an actual string from that.

**Comment by madmikep** [comment]
I have two servers configured the same way DEV and QA  both have 3 appPools with the same name using a process ID.   The Dev server works fine.  But the QA server dose not the AppPool stops when you try to access the websites.  I added the Write-Verbose lines and ran the Start-DSCConfiguration and it reported back the encrypted has that's in the MOF file not the password.  I then ran appcmd.exe list apppool "AppPoolName" /text:*  on all 3 apppools and they return for the password the same --- BEGIN CMS ----    HASH  ----END CMS----.    I check the DEV server and it reports the correct password.   Very odd   WMF 5.1

**Comment by madmikep** [comment]
Verbose reports the certificate :"-----BEGIN CMS-----
HASH
-----END CMS-----"

**Comment by jhenders1973** [comment]
Hey Mike....that is exactly the same situation as mine. It´s confusing as hell....as i said in an earlier post maybe this is a lower level IIS issue or maybe macine policy??? Not sure of your set up but certainly on mine i have alot more control Security wise on my QA environment that DEV so maysome sort sort of policy. I gave up looking and just used a work around.....not ideal but Production is up and all Works.

**Comment by jwainwright** [comment]
My issues were resolved by going to WMF 5.1 in the end. I have had no issues since completing the upgrade. However, I did have to change my certificate to a DocumentEncryptionCert certificate for WMF 5.1, but if you have one server that works already I would assume you have done that already. 
Your issue sounds as though you are not decrypting the encrypted password string(which was my original issue). If you open the the cert you are using for encrypt/decrypt with a text editor it will start with "----BEGIN CMS-----"
 When you run Start-DSCConfiguration -Wait -Verbose, do you see a decryption error?

Below is a script to set all of you app pools identities and echo out what they were set to before(Comment the Set-ItemProperty line if you just want to see what they are set to). May help out, but may need to be modified if you have more than one credential on an IIS server.

Import-Module WebAdministration
$Creds = Get-Credential 
$pools = dir IIS:\AppPools
foreach ($pool in $pools){
  if ($pool.Name -like '*_AppPool'){
      Write-Host $pool.Name
      (Get-ItemProperty IIS:\AppPools\$($pool.Name)).ProcessModel.password
      Set-ItemProperty IIS:\AppPools\$($pool.Name) -name processModel -value @{userName="$($Creds.UserName)";password="$($Creds.GetNetworkCredential().password)";identitytype=3}
      $pool.Start()
  }
}

**Comment by madmikep** [comment]
I have been on WMF 5.1 since it came out, it fix a lot of my problems.     Now back to the problemt I have done some more testing on the QA system.   If I configure the LCM to only apply the ConfigurationNames = QA_IntranetMgmt_AppPool.  It will decrypt the password and apply it. If I add more PartialConfiguration to the LCM it goes back to applying the certificate encode as the password.   VERBOSE: [SERVERNAME]:                            [[xWebAppPool]AppPool_MgmtRpt] [Password] -----BEGIN CMS-----
sadasdsadasdkamksamd..............
-----END CMS-----

**Comment by jwainwright** [comment]
Interesting. I wonder does the additional partial configs use different encryption certificates? or no certificate for encryption at all?

**Comment by madmikep** [comment]
The only configuration that uses the encryption is the AppPool one.

**Comment by jwainwright** [comment]
I wonder if you had all of the configuration in one MOF if it would have the same issue or if you add the decryption to the other partial configs if it would work.

**Comment by madmikep** [comment]
I tried it on another test server that I have and the results are the same.  I open the MSFT_xWebAppPool.psm1 and copied the Test-TargetResource Function  I am trying to see where it reads in the credential information from the MOF and where it takes that information and decrypts it and what the result is.

**Comment by madmikep** [comment]
@jwainwright After work on the Test-TargetResource it would not test the credentials and just did not have the time to figure out how it reads in the data from the MOF file.  So I combined all 8 Configurations in to one and combined the 6 HashTables in to one file.  It is now working it creates the 3 AppPools and applies the password correctly and not the certificate encoding.    The only problem now is every time an update is made to the website source files they are zipped up and placed on the Pull server the client check the MD5 hash of the zip file and if it changes its downloaded and unzipped.   Well this requires the MD5 has to be updated in the Hashtable which then requires rerunning the configuration to create a new MOF file.   Now the process ID and password needs to be entered every time.  I think that the LCM is not processing the MOF files correctly.

**Comment by jwainwright** [comment]
@madmikep You said "So I combined all 8 Configurations in to one and combined the 6 HashTables in to one file". What Hashtables are you refering to? Are you referring to the encrypted passwords that start with "-----BEGIN CMS-----". Also, how did you combine them.... did you write a new script to join them or just add them all to the same MOF file manually?

**Comment by leovic0101** [comment]
I have the same issue with partial configuration when using an encrypted password. However, it works when not using partial configurations.

**Comment by johlju** [comment]
What I can gather from the conversation is that there are a problem running this using partial configurations? Does someone have a partial configurations that fails that they can share (obfuscate any sensitive information), and the same configurations concatenated into one configuration that works?
